nnUNetv2_plan_and_preprocess -d 509 --verify_dataset_integrity
nnUNetv2_train 509 3d_fullres all

python merge.py
python train.py --in-fpath ./datasets/Brain_datasets/trainnew --weight-dir ./checkpoints/Brain_datasets/smore_2channel/foldall  --gpu-id 0 --slice-thickness 4 --target-thickness 1.0 --num-slices 1  --lr 0.0005  --n-patches 8320000 --random-flip --preload
python test.py --in-fpath ./datasets/Brain_datasets/trainnew --out-fpath ./checkpoints/Brain_datasets/smore_2channel/eval --ref-fpath ./data/Brain_datasets/Meningioma_converted_preprocessed_lr  --weight-dir ./checkpoints/Brain_datasets/smore_2channel/foldall --epoch latest --slice-thickness 4.0 --target-thickness 1.0
python convert_h5.py
python train.py --in-fpath ./datasets/Brain_datasets/trainnew_h5 --weight-dir ./checkpoints/Brain_datasets/flavr_pretrained_2channel/foldall  --gpu-id 0 --slice-thickness 4 --target-thickness 1.0 --num-slices 4 --patch-size 96 --lr 0.0005 --batch-size 64 --n-patches 8320000 --pretrain-path ../../FLAVR/checkpoints/FLAVR_4x.pth --random-flip --preload --nnunet-transform
python train.py --in-fpath ./datasets/Brain_datasets/trainnew_h5 --weight-dir ./checkpoints/Brain_datasets/flavr_pretrained_2channel_uncertainty/foldall  --gpu-id 0 --slice-thickness 4 --target-thickness 1.0 --num-slices 4 --patch-size 96 --lr 0.0005 --batch-size 64 --n-patches 8320000 --pretrain-path ./checkpoints/Brain_datasets/flavr_pretrained_2channel/foldall/last_weights.pt --random-flip --preload --enable-uncertainty --nnunet-transform
python test_3d.py --in-fpath ./datasets/Brain_datasets/trainnew --out-fpath ./checkpoints/Brain_datasets/flavr_pretrained_2channel_uncertainty/eval --ref-fpath ./data/Brain_datasets/Meningioma_converted_preprocessed_lr  --weight-dir ./checkpoints/Brain_datasets/flavr_pretrained_2channel_uncertainty/foldall --epoch 20000 --slice-thickness 4.0 --target-thickness 1.0 --enable-uncertainty

python train_segsr_efficient.py --in-fpath ../../../data/Inhouse_datasets/trainnew_resample_sr_h5 --weight-dir ./checkpoints/Brain_datasets/segsr_uncertainty_distillation/fold0 --gpu-id 0 --slice-thickness 3.0 --target-thickness 0.75   --resume-sr-path ./checkpoints/Brain_datasets/flavr_pretrained_2channel_uncertainty/foldall/weights_20000.pt --resume-seg-path ../../nnUNet/DATASET/nnUNet_results/Dataset509_BoneTumor/nnUNetTrainer__nnUNetPlans__3d_fullres/fold_0/checkpoint_final.pth --plan-file ../../nnUNet/DATASET/nnUNet_results/Dataset509/nnUNetTrainer__nnUNetPlans__3d_fullres/plans.json --split-path ../../nnUNet/DATASET/nnUNet_preprocessed/Dataset509_BoneTumor/splits_final.json --val-img-path ../../nnUNet/DATASET/nnUNet_raw/Dataset509_BoneTumor/imagesTr --val-label-path ../../nnUNet/DATASET/nnUNet_raw/Dataset509_BoneTumor/labelsTr --save-iters 500 --num-epochs 500 --fold 0 --random-flip --lr 1e-3 --enable-uncertainty --enable-distillation --lambda_l1 0.0 --lambda_structure 1.0